- hosts: datanode
  tasks:
   - name: "downloading jdk"
     get_url:
      url: http://35.244.242.82/yum/java/el7/x86_64/jdk-8u171-linux-x64.rpm
      dest: /root/jdk-8u171-linux-x64.rpm
      mode: '0644'

   - shell: "rpm -q jdk-8u171-linux-x64.rpm"
     register: java_result
   - debug:
      var: java_result.stdout

   - shell: "rpm -i jdk-8u171-linux-x64.rpm"
     when: java_result.stdout != "jdk1.8-1.8.0_171-fcs.x86_64"
   
 
